---
- name: Converge
  hosts: all
  tasks:
    - name: Include vars
      include_vars: "../../../../inventories/group_vars/password-encrypt.yaml"
    - name: "Include instana_demo.update_was_config"
      include_role:
        name: "instana_demo.update_was_config"
