---
- name: Skip task
  debug:
    msg: "cockroachdb is unimplemented!"

# - name: Copy dump file into /tmp
#   become: true
#   copy:
#     src: "pattern-{{ import_pattern }}.tar"
#     dest: /tmp/cockroachdb_dump.tar

# - name: Copy cockroachdb_dump.tar into container
#   become: true
#   command: docker cp -a /tmp/cockroachdb_dump.tar instana-cockroachdb:/tmp

# - name: Extract cockroachdb_dump.tar into /tmp
#   become: true
#   community.docker.docker_container_exec:
#     container: instana-cockroachdb
#     command: tar -xf /tmp/cockroachdb_dump.tar

# - name: Create cockroachdb local node file system
#   become: true
#   community.docker.docker_container_exec:
#     container: instana-cockroachdb
#     command: mkdir -p /mnt/data/extern/

# - name: Get old tenant_unit_id
#   become: true
#   community.docker.docker_container_exec:
#     container: instana-cockroachdb
#     command: head -n 1 /tmp/cockroachdb_dump/tenant_unit_id.txt
#   register: old_tenant_unit_id

# - name: Get new tenant_unit_id
#   become: true
#   community.docker.docker_container_exec:
#     container: instana-cockroachdb
#     command: /opt/instana/cockroachdb/cockroach sql --insecure -d tenantdb -e 'SELECT id FROM tenant_units'
#   register: new_tenant_unit_id

# - name: Import dump file
#   include_tasks: import_cockroachdb.yml
#   with_items:
#   - "{{ instana_table_dics.keys() }}"

# - name: Remove dump directory in container
#   become: true
#   community.docker.docker_container_exec:
#     container: instana-cockroachdb
#     command: rm -rf /tmp/cockroachdb_dump

# - name: Remove cockroachdb_dump.tar
#   become: true
#   community.docker.docker_container_exec:
#     container: instana-cockroachdb
#     command: rm /tmp/cockroachdb_dump.tar

# - name: Remove dump file
#   become: true
#   file:
#     path: /tmp/cockroachdb_dump.tar
#     state: absent