---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider: 
    name: virtualbox
platforms:
  - name: instance-common
    box: "generic/rhel8"
provisioner:
  name: ansible
  connection_options:
    env_name_color: 32
    time_color: 35
    hostname_color: 32
    current_path_color: 34
    hostname: test.demo.ibmcloud.com
verifier:
  name: ansible
